#!/usr/bin/env bash
#This is performing nginx installation

sudo apt-get update
sudo apt-get install -y nginx

sudo ufw allow 'Nginx HTTP'


echo "Hello World!" | sudo tee /var/www/html/index.html

# Testing Nginx configurations for Syntax errors
sudo nginx -t


sudo sevice nginx restart
