#!/usr/bin/env bash
# implementing http_response_header

# Updating Packages before performing installations
# sudo apt-get update
# sudo apt-get install -y nginx

# Creating an index.html page
# echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a "moved permanently redirection" (301)
string_1="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/hancho6319 permanent;"
# sudo sed -i "s/server_name _;/$string_1/" /etc/nginx/sites-enabled/default

# Creating a 404 Custom error page
# echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
# string_2="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

# sudo sed -i "s/listen 80 default_server;/$string_2/" /etc/nginx/sites-enabled/default

# Creating an HTTP response header
sudo sed -i "/server_name _/a \tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# Testing the configurations syntax for any error
sudo nginx -t

# Restart the nginx
sudo service nginx restart
